using System;
using System.CodeDom;

namespace wcg.CodeGeneration
{
    internal class AddComments : IPostProcessor
    {
        public void PostProcess(CodeNamespace codeNamespace)
        {
            codeNamespace.Comments.Add(GetAutoGeneratedComment(Environment.Version.ToString()));
            codeNamespace.Comments.Add(GetCodeComment(ApplicationUtilities.Application, ApplicationUtilities.Version));
        }

        public string SchemaNamespace { get; set; }

        private CodeCommentStatement GetCodeComment(string applicationName, string applicationVersion)
        {
            return new CodeCommentStatement(@"
 This source code was auto-generated by " + applicationName + @", Version=" + applicationVersion + @"
 ");
        }

        private CodeCommentStatement GetAutoGeneratedComment(string runtimeVersion)
        {
            return new CodeCommentStatement(@"------------------------------------------------------------------------------
 <auto-generated>
     This code was generated by a tool.
     Runtime Version:" + runtimeVersion + @"
     
     Changes to this file may cause incorrect behavior and will be lost if
     the code is regenerated.
 </auto-generated>
------------------------------------------------------------------------------");
        }
    }
}
